### ISSUE TITLE
Completely disable  stripe if no API key provided

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1388]
ATM running a devel instance off `env/ohbm` results in console showing following traceback

<details>
<summary>traceback</summary> 

```shell
v3:1 Uncaught (in promise) IntegrationError: Please call Stripe() with your publishable key. You used an empty string.
    at new o (https://js.stripe.com/v3:1:2923)
    at yi (https://js.stripe.com/v3:1:155638)
    at new xu (https://js.stripe.com/v3:1:232159)
    at Lu (https://js.stripe.com/v3:1:233101)
    at initStripe (http://localhost:3000/static/js/vendors~main.chunk.js:64747:28)
    at http://localhost:3000/static/js/vendors~main.chunk.js:64771:12
o @ v3:1
yi @ v3:1
xu @ v3:1
Lu @ v3:1
initStripe @ stripe.esm.js:101
(anonymous) @ stripe.esm.js:125
Promise.then (async)
Elements @ react-stripe.umd.js:344
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
scheduleUpdateOnFiber @ react-dom.development.js:21188
updateContainer @ react-dom.development.js:24373
(anonymous) @ react-dom.development.js:24758
unbatchedUpdates @ react-dom.development.js:21903
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24757
render @ react-dom.development.js:24840
(anonymous) @ index.tsx:272
unstable_trace @ scheduler-tracing.development.js:87
(anonymous) @ index.tsx:271
./src/index.tsx @ index.tsx:301
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ wdyr.js:9
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1

```
</details>

I don't see it while browsing https://ohbm.sparkle.space/in/home but didn't check if it may be just that the instance does have API key set, and thus it does spend time on each page load to communicate to stripe.  AFAIK we do not need stripe service for the event, and any additional communication == "delay/waste", so would be nice to be able to cleanly "cut off" services which are not involved.

**Comment by 0xdevalias** [comment]
The `env/ohbm` environment would be configured with our default stripe credentials as part of our standard environment setup. It should be fairly easy for me to remove that from our build system config, but then you'll just end up seeing the warning as you do locally.

I haven't looked into what's involved to fix that.

**Comment by yarikoptic** [comment]
I thought to go with the
<details>
<summary>patch like this</summary> 

```patch
diff --git a/src/index.tsx b/src/index.tsx
index 059a1fe3..0724b664 100644
--- a/src/index.tsx
+++ b/src/index.tsx
@@ -99,17 +99,18 @@ if (process.env.NODE_ENV === "development") {
   firebaseFunctions.useFunctionsEmulator("http://localhost:5001");
 }
 
-// Load Stripe
-const traceStripeLoad = createPerformanceTrace(
-  PerformanceTrace.initStripeLoad,
-  {
-    startNow: true,
-  }
-);
-const stripePromise = loadStripe(STRIPE_PUBLISHABLE_KEY ?? "").finally(() => {
-  traceStripeLoad.stop();
-});
-
+// Load Stripe if key is setup
+if (STRIPE_PUBLISHABLE_KEY != "") {
+  const traceStripeLoad = createPerformanceTrace(
+    PerformanceTrace.initStripeLoad,
+    {
+      startNow: true,
+    }
+  );
+  const stripePromise = loadStripe(STRIPE_PUBLISHABLE_KEY).finally(() => {
+    traceStripeLoad.stop();
+  });
+}
 const rrfConfig = {
   userProfile: "users",
   useFirestoreForProfile: true,

```
</details>

but then we would need to make `Elements` for `stripePromise` conditioned in the

<details>
<summary>traceReactScheduler</summary> 

```shell
traceReactScheduler("initial render", performance.now(), () => {
  render(
    <BugsnagErrorBoundary>
      <ThemeProvider theme={theme}>
        <Elements stripe={stripePromise}>
          <DndProvider backend={HTML5Backend}>
            <Provider store={store}>
              <ReactReduxFirebaseProvider {...rrfProps}>
                <AuthIsLoaded>
                  <CustomSoundsProvider
                    loadingComponent={<LoadingPage />}
                    waitTillConfigLoaded
                  >
                    <AppRouter />
                  </CustomSoundsProvider>
                </AuthIsLoaded>
              </ReactReduxFirebaseProvider>
            </Provider>
          </DndProvider>
        </Elements>
      </ThemeProvider>
    </BugsnagErrorBoundary>,
    document.getElementById("root")
  );
});
```
</details>

what would be the kosher way for that?

**Comment by 0xdevalias** [comment]
> but then we would need to make `Elements` for `stripePromise` conditioned in the

I'd probably follow a similar pattern as used to stub out `Bugsnag`:

```typescript
// When BUGSNAG_API_KEY not set, stub out BugsnagErrorBoundary with a noop
const BugsnagErrorBoundary = BUGSNAG_API_KEY
  ? Bugsnag.getPlugin("react")?.createErrorBoundary(React) ?? React.Fragment
  : React.Fragment;
```

So we would probably want something like the following I would expect:

```typescript
const StripeElementsProvider = STRIPE_PUBLISHABLE_KEY ? Elements : React.Fragment;
```

Then use `StripeElementsProvider` in place of `Elements` in the `render`'s JSX.
