### ISSUE TITLE
Clicking "Happening now" button on Schedule / event dialog crashes

### ISSUE THREAD

**Issue by soichih** [sparkletown/sparkle#1622]
When I click on an event and then click "Happening now in ..." button, 

![image](https://user-images.githubusercontent.com/923896/122859987-eb7dc300-d2ea-11eb-92e0-708386622a34.png)

it crashes with this error message.

```
build.umd.js:645 Uncaught DOMException: Failed to set the 'href' property on 'Location': '//' is not a valid URL.
    at openUrl (https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:78214)
    at openRoomUrl (https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:123297)
    at enterExternalRoom (https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:123365)
    at https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:126408
    at goToEventLocation (https://ohbm.sparkle.space/static/js/main.c4b94700.chunk.js:1:127655)
    at Object.ba (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2022140)
    at ia (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2022317)
    at ja (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2022489)
    at na (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2022585)
    at kc (https://ohbm.sparkle.space/static/js/2.15386b81.chunk.js:2:2039295)
wrapped @ build.umd.js:645
```

**Comment by 0xdevalias** [comment]
@soichih see the issue and/or PR that @margulies raised about this the other day. It talks about the problem, but doesn’t really get into understanding the ‘why’, and not sure the fix implemented is ideal.
